export interface Products {
    availablity: boolean,
    brand: string,
    category: string,
    category_type: string,
    color: string,
    description: string,
    discount_price: number,
    id: number,
    image: string,
    image_gallery: string,
    name: string,
    popular: boolean,
    price: number,
    product_code: string,
    quantity: number,
    rating: string,
    store_id: number,
    status: boolean,
    type: string,
}
